openshift/cluster-capi-operator

README.md, hack/import-assets/provider-versions.json, hack/import-assets/providers.go
This PR extract provider versions from file instead hardcoded in import-assets utility. It would be better to manage resources in json file. In addition to that, although it is not being used, providerFilter can be used if import-assets is executed directly by user to filter.
=> Extract provider versions from json file in import-assets

manifests/0000_30_capi-operator_00_credentials-request.yaml
Add cloud credentials requests to manifests, for now, it's limited to AWS, GCP and Azure.
=> Add cloud credentials requests to manifests

pkg/controllers/clusteroperator_controller.go, pkg/controllers/operator_status.go
This PR temporarily disables operator reconciliation. After CVO started managing all manifests, we need to refactor the operator. With the current implementation, it tries to install AWS provider and some CRDs are missing, this causes tests to fail.
=> Disable operator reconciliation

manifests/0000_30_capi-operator_00_credentials-request.yaml
For enabling short-lived credentials in aws and gcp clusters using workload
identity, we need ccoctl tool to know the kubernetes service account
names from the credentials request manifest so that it can create
aws and gcp service accounts that can be impersonated only by specific
kubernetes service accounts.
ref:
https://github.com/openshift/machine-api-operator/commit/1f3a083fe50c0e80106ca336878725f142173aba
=> Bug 2037061: Add service account names to aws and gcp credentials request manifest

cluster-api-operator.yaml, manifests/0000_30_cluster-api_capi-operator_02_providers.configmap.yaml, providers-list.yaml
Set a release branch for manifests, this should help with backports later and we can always see where manifests are coming from.
=> Set a release branch for manifests

manifests/0000_30_cluster-api_00_credentials-request.yaml
CAPA attaches security groups to network interfaces after instance creation, this requires new permissions. In MAPI we specify security groups on instance creation that's we don't have these permissions for MAPI.
=> Add network interfaces permissions for aws

pkg/controllers/clusteroperator/clusteroperator_controller.go
This change is being added to temporarily disable deployment of the
operator so that it does not break tests on architectures which have not
had their images creeated yet. For extended discussion of this decision,
please see the conversation[0] in coreos slack.
[0]
https://coreos.slack.com/archives/C01CQA76KMX/p1647367797409909?thread_ts=1647351322.648249&cid=C01CQA76KMX
=> disable deployment of capi operator

cmd/cluster-capi-operator/main.go, go.mod, pkg/controllers/cluster/aws_test.go, pkg/controllers/cluster/cluster_test.go, pkg/controllers/cluster/suite_test.go, pkg/controllers/clusteroperator/clusteroperator_controller.go, pkg/controllers/clusteroperator/components_test.go, pkg/controllers/kubeconfig/generate.go, pkg/controllers/kubeconfig/generate_test.go, pkg/controllers/kubeconfig/kubeconfig.go, pkg/controllers/kubeconfig/kubeconfig_test.go, pkg/controllers/kubeconfig/suite_test.go, pkg/controllers/secretsync/secret_sync_controller.go, pkg/controllers/secretsync/secret_sync_controller_test.go, pkg/test/cleanup.go
Add controller that creates a kubeconfig from operators service account. This kubeconfig is tied to cluster object will be used by CAPI to link nodes and machines.
=> Add kubeconfig controller

Makefile
This PR contains two fixes for Cluster CAPI operator CI:
1. It bumps envtest version.
2. It starts using `go install` to fetch testing binaries.
=> Fix some CI issues

manifests/0000_30_cluster-api_capi-operator_02_service_account.yaml, pkg/controllers/kubeconfig/kubeconfig.go, pkg/controllers/kubeconfig/kubeconfig_test.go
Create service account secret manually as described here, https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/ Current implementation will not work on 1.24 because the secret for SA is not created automatically anymore.
=> Create service account secret manually

manifests/0000_30_cluster-api_capi-operator_02_service_account.yaml
The secret should be created in `openshift-cluster-api` namespace.
=> Bug 2084545: Create cluster-capi-operator-secret in right namespace

pkg/controllers/kubeconfig/kubeconfig.go, pkg/controllers/kubeconfig/watch_predicates.go
Now it doesn't react on changes in the managed secrets, which allows users to modify them.
=> Bug 2087149: Add watch predicates to kubeconfig controller

Makefile, hack/assets.sh, hack/assets/main.go, hack/assets/providers.go
Currently when we run `make assets`  all providers get updated. With a growing provider list, it takes a long time. This PR adds an option to choose a provider to update. For example: `PROVIDER=operator make assets`
=> Add option to choose a provider to update

manifests/0000_30_cluster-api_00_namespace.yaml
Currently the operator can't run because pod security admission is enforced and we don't have the correct configuration.
For now, we run this as privileged (xref https://github.com/openshift/machine-api-operator/pull/924) but over time will restrict this down as per the requirements of the workloads in this project.
=> Set privileged pod security for openshift-cluster-api namespace

cmd/cluster-capi-operator/main.go
Cluster API on OpenShift is in TechPreview and available only for a limited number of providers: AWS, GCP.
This PR disables Azure as a supported platform, until that will be deemed ready for TechPreview.
=> Bug 2118550: Momentarily disable Azure platform support

cmd/cluster-capi-operator/main.go, manifests/0000_30_cluster-api_02_webhook-service.yaml, manifests/0000_30_cluster-api_10_webhooks.yaml, pkg/webhook/cluster.go, pkg/webhook/coreprovider.go, pkg/webhook/infraprovider.go
This PR starts the implementation of the validation webhooks for CAPI objects.
In particular, it validates that Cluster object infrastructure reference has correct value.
=> Bug 2116686, Bug OCPBUGS-1493: Initial implementation of validation webhooks

cmd/cluster-capi-operator/main.go, manifests/0000_30_cluster-api_10_webhooks.yaml, pkg/webhook/provider.go
To prevent deletion of created Cluster API providers we add a webhook to check this operation.
Also this commit enables missing operations for other webhooks.
=> Bug 2116686: OCPBUGS-1493: Add provider webhook

pkg/controllers/cluster/core.go, pkg/controllers/cluster/infra.go, pkg/util/patch.go
Currently we send a request to update some objects on each reconciliation, even if these objects were not modified.
To prevent this we introduce checks to ensure that changes were made before sending patch requests.
=> Don't patch objects if there are no changes

e2e/aws_test.go, e2e/gcp_test.go, e2e/powervs_test.go
Currently we skip only BeforeAll part of our tests, but AfterEach is executed on each platform which leads to panics.
```
Skipping AWS E2E tests
In [BeforeAll] at: /home/mfedosin/projects/cluster-capi-operator/e2e/aws_test.go:41
Full Stack Trace
github.com/openshift/cluster-capi-operator/e2e.glob..func1.1()
/home/mfedosin/projects/cluster-capi-operator/e2e/aws_test.go:41 +0x10c
There were additional failures detected after the initial failure:
[PANICKED]
Test Panicked
In [AfterEach] at: /usr/local/go/src/runtime/panic.go:260
runtime error: invalid memory address or nil pointer dereference
Full Stack Trace
github.com/openshift/cluster-capi-operator/e2e/framework.DeleteMachineSets({0x3df5318, 0xc000812540}, {0xc000943ec8, 0x1, 0x0?}) …
```
=> Fix panics in e2e tests

manifests/0000_30_cluster-api_10_webhooks.yaml
Despite the fact the indentation is correct, these manifests are not correctly parsed by CVO, and some fields are missing.
To fix it we update the indentation to bring it to a more standard variant.
=> fix indentation for webhook manifests

pkg/webhook/cluster.go
We want only one Cluster in the openshift-cluster-api namespace that creates machines for the cluster we are running on. To prevent creation of multiple clusters, this PR adds webhook that allows only clusters named <InfrastructureName> that is obtained from the InfrastructureObject.
=> OCPBUGS-4147: Enforce single Cluster in openshift-cluster-api namespace

pkg/webhook/cluster.go
While this field is marked optional in the API, it does not make much sense, as clusters without infrastructureRef are not able to create machines. Allowing these configurations causes panic in other capi components that expect this value to be set.
=> OCPBUGS-9970: Make infrastructureRef field required

hack/assets/customizations.go, manifests/0000_30_cluster-api_02_crd.core-cluster-api.yaml
Removing a filter which was introduced in cluster-capi-operator#8 and refactored in cluster-capi-operator#34 to filter out the metal3 ipam types.  The metal 3 IPAM types were dropped in cluster-capi-operator#23.  As a result, removing the check so the current CAPI IPAM CRDs can be installed in support of [vSphere static IP efforts](https://issues.redhat.com/browse/SPLAT-827).
=> SPLAT-1084: Remove IPAM CRD installation filter

assets/infrastructure-providers/infrastructure-azure.yaml, e2e/aws_test.go, e2e/e2e_test.go, hack/clusters/create-aws.sh, hack/clusters/templates/aws.yaml, manifests/0000_30_cluster-api_02_crd.infrastructure-azure.yaml
This sets the ControlPlaneEndpoint before Cluster object creation. To make the Cluster go into `Provisioned` state.
This is a temporary workaround, as we expect the Cluster & InfrastructureCluster objects creation and the population of the ControlPlaneEndpoint is going to happen in a dedicated controller within the operator.
=> OCPBUGS-18504: e2e: set ControlPlaneEndpoint in AWSCluster

assets/infrastructure-providers/infrastructure-ibmcloud.yaml, hack/assets/providercustomizations.go
`powervs-provider-id-fmt` flag is deprecated and we are supposed to use `provider-id-fmt` flag. [Reference](https://github.com/openshift/cluster-api-provider-ibmcloud/blob/main/main.go#L168C2-L175)
=> MULTIARCH-3761: Power VS CAPI Remove deprecated flag

manifests/0000_30_cluster-api_02_providers.configmap.yaml, providers-list.yaml
It is causing issues and we don't leverage it yet.
=> OCPBUGS-22403: Disable CAPI Azure Infrastructure Provider

assets/infrastructure-providers/infrastructure-azure.yaml, manifests/0000_30_cluster-api_02_crd.infrastructure-azure.yaml
When the carry patch https://github.com/openshift/cluster-api-provider-azure/pull/274 was merged, `make assets` wasn't rerun on the cluster-capi-operator.
To fix this we need to rerun asset generation and check in the changes showing up.
=> [release-4.14] OCPBUGS-22314: fix: add missing azure identity diff

pkg/controllers/secretsync/secret_sync_controller.go, pkg/controllers/secretsync/secret_sync_controller_test.go
There is a consensus in the upstream community, that every provider, that supports ignition as its bootstrapping method should adopt field `format` with value `ignition` (encoded as base64 string) to indicate that the user intends to use this feature. If this value would be empty, the upstream providers operator would assume that the user wants to use the other option called `cloud-init` that we don't intend to support in the future.
=> OCPBUGS-19841: Add format key into the worker-user-data secret

manifests/0000_30_cluster-api_10_webhooks.yaml
The resource was renamed to `cluster-capi-operator` in 1096d5c8ee (#132), and that's a much more specific name for the cluster-scoped resource.  However, clusters upating from 4.15.0-ec.1 with the old name should not have two similar-but-not-quite-matching versions of the webhook configuration, or updates can stick with `cluster-api` ClusterOperator going `Degraded=True` on `SyncingFailed` [with][1]:
Failed to resync for operator: 4.15.0-ec.2 because &{%!e(string=unable to reconcile CoreProvider: unable to create or update CoreProvider: Internal error occurred: failed calling webhook "vcoreprovider.operator.cluster.x-k8s.io": failed to call webhook: the server could not find the requested resource)}
This commit adds [a deletion manifest][2] to ask the cluster-version operator to remove …
=> OCPBUGS-23467: manifests/0000_30_cluster-api_10_webhooks: Deletion manifest for validating-webhook-configuration

pkg/webhook/cluster.go
This PR changes the Cluster delete webhook, so that it will only prevent deletion when the cluster is in openshift-cluster-api namespace.
=> OCPBUGS-19842: Limit deletion webhook to openshift namespace

assets/infrastructure-providers/infrastructure-azure.yaml, manifests/0000_30_cluster-api_00_credentials-request.yaml, manifests/0000_30_cluster-api_02_crd.infrastructure-azure.yaml
Instead of using predefined roles on Azure, we want to use granular permissions to gain more control of what can be done on the cluster.
=> OCPCLOUD-2012: Add granular permissions for Azure

pkg/controllers/capiinstaller/component_customizer.go
Also remove openstack from image replacement as openstack is not in cluster-capi-operator's image-references and does its own release image substitution anyway.
=> OCPBUGS-24301: openstack: Don't substitute manager container command

cmd/cluster-capi-operator/main.go, pkg/controllers/cluster/core.go, pkg/controllers/cluster/infra.go, pkg/controllers/kubeconfig/kubeconfig.go, pkg/controllers/unsupported/suite_test.go, pkg/controllers/unsupported/unsupported_controller.go, pkg/controllers/unsupported/unsupported_controller_test.go, pkg/controllers/unsupported/watch_predicates.go, pkg/operatorstatus/operator_status.go
Relying only on the CAPI provider (transport) ConfigMap to be or not to be there, to decide whether to enable CAPI on a platform or not, is not always sufficient as while we develop we may want to add a ConfigMap without actually enabling the controller.
Moreover without this in place we would always setup the Core CAPI provider and the operator webhooks even on platforms which are not supported, which is wasteful and not ideal.
As such we want to start the operator controllers and set up webhooks only on supported platforms.
When the operator is running on a platform where CAPI is not supported, run the unsupported controller instead.
=> OCPBUGS-28539: Start operator controllers only on supported platforms, add unsupported controller

manifests-gen/customizations.go, manifests-gen/providers.go
Store Core CAPI CRDs also in their own manifest to get them applied by CVO directly. We want these to be installed independently from whether the cluster-capi-operator is enabled, as other Openshift components rely on them.
=> OCPBUGS-29476: manifests-gen: store core capi crds also in their own manifest

manifests-gen/customizations.go, manifests-gen/providers.go
Together with the `TechPreviewNoUpgrade` `release.openshift.io/feature-set` we also need to add  `CustomNoUpgrade` as that is used in certain scenarios where CAPI provider ConfigMaps and CRDs are required.
=> OCPBUGS-29519: manifests-gen: also add CustomNoUpgrade annotation value

manifests/0000_30_cluster-api_11_deployment.yaml
found in https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-ci-4.16-e2e-azure-ovn-techpreview-serial/1785629293024382976
We want to be sure we are getting logs from failed containers.
=> OCPBUGS-28230: enforce termination message policy on all platform pods

manifests-gen/customizations.go
In 4.17, we are enforcing this value for all OpenShift containers via tests, link in bug comment. This helps with debugging to ensure we have logs available.
=> OCPBUGS-33170: All containers must fallback to logs on error

hack/e2e-openstack.sh
Align openstack e2e branch, as it would otherwise go out of sync with the go version used in the two projects.
Based on https://github.com/openshift/cluster-api-provider-aws/blob/master/openshift/e2e-tests.sh
=> OCPBUGS-37718: fix: align openstack e2e branch

manifests-gen/providers.go
The transport configMap metadata would get entirely overridden when setting components rather than it being additive.
This is a regression introduced by #170
=> OCPBUGS-39298: manifests-gen: fix: readd missing metadata

manifests-gen/customizations.go
`openshift/cluster-api-provider-metal3` requires certain `ConfigMap`s to be installed in order for the deployment to start.  We add them to the list here so they can have their namespaces updated.
=> METAL-966: manifests-gen: process ConfigMaps

go.mod, go.sum, pkg/conversion/capi2mapi/aws.go, pkg/conversion/capi2mapi/machine.go, pkg/conversion/capi2mapi/machineset.go, pkg/conversion/mapi2capi/aws.go, pkg/conversion/mapi2capi/aws_fuzz_test.go, pkg/conversion/mapi2capi/aws_test.go, pkg/conversion/mapi2capi/machine.go, pkg/conversion/mapi2capi/machineset.go, pkg/conversion/mapi2capi/suite_test.go, pkg/conversion/test/fuzz.go, vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/matchers.go, vendor/modules.txt
This PR adds fuzz conversion testing between MAPI machines to CAPI machines and back again, the idea is that, bar some exceptions where we cannot currently convert, we can round trip the machines and produce the same result at the other end.
Where there are things that we cannot convert, they will be tagged with the appropriate stories to fix the feature gaps and then updated once the gaps are added.
The intention here is to create a pattern for fuzz testing and libraries so that this is easy for other platforms to implement similar.
=> OCPCLOUD-2750: Add fuzz conversion testing for MAPI2CAPI conversions

pkg/conversion/capi2mapi/aws.go, pkg/conversion/mapi2capi/aws.go
Updates comment for the mapi->capi conversion of deviceIndex in aws providerSpec.
No change required for capi->mapi as deviceIndex is stored inside the NetworkInterfaces field, which is already disabled due to being unsupported.
=> OCPCLOUD-2707: Clarify why DeviceIndex is always zero

pkg/conversion/capi2mapi/aws.go, pkg/conversion/capi2mapi/aws_fuzz_test.go, pkg/conversion/capi2mapi/suite_test.go, pkg/conversion/mapi2capi/aws.go, pkg/conversion/mapi2capi/aws_fuzz_test.go, pkg/conversion/mapi2capi/machine.go, pkg/conversion/test/fuzz.go
This follows on from #208 and adds conversion round trip fuzz testing for the CAPI to MAPI side of the equation.
=> OCPCLOUD-2750: Add CAPI2MAPI Machine(Set) fuzz testing

pkg/controllers/machinesync/machine_sync_controller.go, pkg/controllers/machinesync/suite_test.go, pkg/test/crdbuilder.go, pkg/test/envtest.go
This change adds the logic to split the reconciliation depending on which MachineAuthority is set.
=> OCPCLOUD-2643: MachineSyncReconciler - split reconciles

cmd/machine-api-migration/main.go, pkg/controllers/machinesetsync/machineset_sync_controller.go, pkg/controllers/machinesetsync/machineset_sync_controller_test.go, pkg/controllers/machinesetsync/suite_test.go, pkg/controllers/machinesync/machine_sync_controller.go, pkg/util/watch_filters.go
-> Bootstraps MachineSet Sync controller
-> Adds basic test suite & empty test.
-> Fetches resources + dynamic watching of InfraMachineTemplates
=> OCPCLOUD-2643: MachineSetSync controller bootstrap

pkg/controllers/machinesetsync/machineset_sync_controller.go, pkg/controllers/machinesetsync/suite_test.go, pkg/controllers/machinesync/machine_sync_controller.go, pkg/test/crdbuilder.go, pkg/test/envtest.go
-> Updates MachineSetSync reconciler to not return an error if AuthoritativeAPI has an unexpected value
-> Adds split reconciliation logic to split the reconciliation depending on which MachineAuthority is set.
-> Reworks MachineSet test suite to use helper funcs from `/pkg/test`
-> Updates helper funcs in `/pkg/test` to contain fake MachineSet CRD
=> OCPCLOUD-2643: Machinesetsync split reconcile

cmd/cluster-capi-operator/main.go
Following up from https://github.com/openshift/cluster-capi-operator/pull/210 the logic was wrong and kept setting up the normal reconcilers even after the NoopReconciler was set up. This should instead be set up as an alternative to the other controllers in the case of running on ASH.
=> OCPBUGS-42490: fix: azure: do not deploy CAPI on AzureStackCloud

go.mod, go.sum, pkg/conversion/capi2mapi/aws.go, pkg/conversion/capi2mapi/aws_test.go, pkg/conversion/capi2mapi/machine.go, pkg/conversion/capi2mapi/machine_test.go, pkg/conversion/capi2mapi/machineset_test.go, vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/cluster-api/core/v1beta1/cluster.go, vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/cluster-api/core/v1beta1/machine.go, vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/cluster-api/core/v1beta1/machineset.go, vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/cluster-api/infrastructure/v1beta2/awscluster.go, vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/cluster-api/infrastructure/v1beta2/awsmachine.go, vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/cluster-api/infrastructure/v1beta2/awsmachinetemplate.go, vendor/modules.txt
Second part (following up from the first https://github.com/openshift/cluster-capi-operator/pull/215) of the negative unit testing efforts for the conversion packages.
This is for the capi2mapi pkg.
=> OCPCLOUD-2749: capi2mapi conversion pkg negative testing

manifests-gen/README.md, manifests-gen/main.go, manifests-gen/providers.go
This PR adds the ability to locally override the path for Kustomize components within a CAPI provider repository.
This is required for https://github.com/openshift/cluster-api-provider-azure/pull/322 so that the Azure Service Operator's Deployment arguments can be overridden to ignore handling CRDs. 
Adding that modification directly in the Go code here would create a tighter coupling between this repository and the CAPZ one, and would be less flexible for future scenarios.
Also added a README file to explain some assumptions in the code base and document overriding the Kustomize component path.
=> OCPCLOUD-2642: manifests-gen: Allow overriding kustomize component path

go.mod, go.sum, pkg/controllers/machinesetsync/machineset_sync_controller.go, pkg/controllers/machinesetsync/machineset_sync_controller_test.go, vendor/modules.txt
This PR adds tests outside of the happy path for the MachineSetSync controller going in the direction from capi -> mapi 
#221 should merge before this.
=> OCPCLOUD-2646: MachineSetSync controller: tests

cmd/machine-api-migration/main.go, manifests/0000_30_cluster-api_11_deployment.yaml
This change:
Removes the defaulting in the code where we set DiagnosticsAddress. It was being overwritten by --diagnostics-address in capiflags.AddManagerOptions() and setting the default value to :8443.
Updates the deployment manifests to pass --diagnostics-address to the migration controller with a value of :8442, so we don't clash with the cluster-capi-operator container running in the pod.
=> OCPCLOUD-2787: Updates migration cmd to change metrics port

manifests/image-references
Draft until https://github.com/openshift/release/pull/55371 merges and the image is actually built.
=> OCPCLOUD-2642: Reference ASO image for installation

pkg/controllers/corecluster/corecluster_controller_test.go, pkg/controllers/unsupported/suite_test.go, pkg/controllers/unsupported/unsupported_controller_test.go, pkg/operatorstatus/operator_status.go
For manual testing of this fix, see: https://github.com/openshift/cluster-capi-operator/pull/248#issuecomment-2592344932
**Problem:**
Prior to this change, the operator's controller responsible for keeping the ClusterObject up to date had an issue when invoking r.SetStatusAvailable(...) with a non-empty availableConditionMsg string. Specifically:
- The condition NewClusterOperatorStatusCondition(configv1.OperatorAvailable, configv1.ConditionTrue, ReasonAsExpected, availableConditionMsg) would remain unchanged.
- This left the conds []configv1.ClusterOperatorStatusCondition unmodified compared to the current ClusterObject.Status.Conditions. 
- As a result, the ClusterObject.Status was not resynced.
This behavior caused a critical issue during cluster version upgrades:
- The operator failed …
=> OCPBUGS-29815: fix: always update clusteroperator status versions when differing

Makefile, pkg/controllers/cluster/core_test.go, pkg/controllers/cluster/suite_test.go, pkg/controllers/unsupported/suite_test.go, pkg/controllers/unsupported/unsupported_controller_test.go, pkg/operatorstatus/operator_status.go
Manual backport of https://github.com/openshift/cluster-capi-operator/pull/248
---
**Problem:**
Prior to this change, the operator's controller responsible for keeping the ClusterObject up to date had an issue when invoking r.SetStatusAvailable(...) with a non-empty availableConditionMsg string. Specifically:
The condition NewClusterOperatorStatusCondition(configv1.OperatorAvailable, configv1.ConditionTrue, ReasonAsExpected, availableConditionMsg) would remain unchanged. This left the conds []configv1.ClusterOperatorStatusCondition unmodified compared to the current ClusterObject.Status.Conditions. As a result, the ClusterObject.Status was not resynced. This behavior caused a critical issue during cluster version upgrades:
The operator failed to propagate changes to …
=> [release-4.18] OCPBUGS-48429: fix: always update clusteroperator status versions when differing

Makefile, pkg/controllers/cluster/core_test.go, pkg/controllers/cluster/suite_test.go, pkg/controllers/unsupported/suite_test.go, pkg/controllers/unsupported/unsupported_controller_test.go, pkg/operatorstatus/operator_status.go
Manual backport of https://github.com/openshift/cluster-capi-operator/pull/249
---
**Problem:**
Prior to this change, the operator's controller responsible for keeping the ClusterObject up to date had an issue when invoking r.SetStatusAvailable(...) with a non-empty availableConditionMsg string. Specifically:
The condition NewClusterOperatorStatusCondition(configv1.OperatorAvailable, configv1.ConditionTrue, ReasonAsExpected, availableConditionMsg) would remain unchanged. This left the conds []configv1.ClusterOperatorStatusCondition unmodified compared to the current ClusterObject.Status.Conditions. As a result, the ClusterObject.Status was not resynced. This behavior caused a critical issue during cluster version upgrades:
The operator failed to propagate changes to …
=> [release-4.17] OCPBUGS-48493: fix: always update clusteroperator status versions when differing

hack/rebasebot-hook-scripts/generate-ocp-manifests.sh
This script will be run by rebasebot during rebase of the CAPI repositories. The location is specified as parameter to it. It is downloaded from this repo and executed on the repo that is being rebased.
=> OCPCLOUD-2824: Add manifest generation script for rebasebot

hack/rebasebot-hook-scripts/update-ocp-manifests-gen.sh
Adds lifecyclehook script that will run make update-manifests-gen in openshift folder in the rebased repository.
This is meant to run before running generate-ocp-manifests.sh hook to ensure manifests-gen is present and up-to-date.
I considered these two scripts being combined, but having the option to quickly disable one is preferred.
=> NO-JIRA: Add lifecyclehook script that updates manifests-gen

pkg/controllers/capiinstaller/capi_installer_controller.go, pkg/controllers/clusteroperator/clusteroperator_controller.go, pkg/controllers/corecluster/corecluster_controller.go, pkg/controllers/corecluster/corecluster_controller_test.go, pkg/controllers/infracluster/infracluster_controller.go, pkg/controllers/secretsync/secret_sync_controller.go, pkg/operatorstatus/operator_status.go
This PR is part of a wider effort to try and rework the controller/operator level condition setting and aggregation for the cluster-capi-operator (see: https://issues.redhat.com/browse/OCPCLOUD-2792)
This PR specifically, builds on top of #254 and:
- defines controller level conditions for the CoreCluster controller, setting them accordingly
- tests that the conditions have been set under different scenarios
More PRs will follow for each controller once the approach proposed in this one is agreed upon.
=> OCPCLOUD-2792: corecluster: set controller level conditions + tests

pkg/conversion/mapi2capi/aws.go, pkg/conversion/mapi2capi/aws_fuzz_test.go, pkg/conversion/mapi2capi/aws_test.go
Hello! This is a draft PR to get feedback for the default VolumeSize for the MAPI to CAPI conversion for AWS. Thanks!
=> OCPCLOUD-2718: Add default VolumeSize for MAPI to CAPI conversion

pkg/controllers/corecluster/corecluster_controller.go
Fixed an issue where PowerVSPlatformType was using incorrect CAPI CRD name. Now, it correctly returns `ibmpowervscluster` as per the [Cluster API Provider for IBM Cloud](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/main/api/v1beta2/ibmpowervscluster_types.go#L247).
=> OCPBUGS-53057: Fix misspelled CAPI IBMPowerVSCluster kind name in corecluster generation logic

pkg/controllers/capiinstaller/capi_installer_controller.go, pkg/controllers/clusteroperator/clusteroperator_controller.go, pkg/controllers/corecluster/corecluster_controller.go, pkg/controllers/corecluster/corecluster_controller_test.go, pkg/controllers/infracluster/infracluster_controller.go, pkg/controllers/secretsync/secret_sync_controller.go, pkg/operatorstatus/operator_status.go
Reverts openshift/cluster-capi-operator#256; tracked by https://issues.redhat.com/browse/OCPBUGS-52848
Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.
This PR has caused samples operator to fail during installation starting from this payload: https://sippy.dptools.openshift.org/sippy-ng/release/4.19/tags/4.19.0-0.nightly-2025-03-05-232901/pull_requests
Slack thread: https://redhat-internal.slack.com/archives/C01CQA76KMX/p1741634385702679
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check …
=> TRT-2048: Revert "OCPCLOUD-2792: corecluster: set controller level conditions + tests"

hack/rebasebot-hook-scripts/generate-ocp-manifests.sh
When writing this script, I thought the version should be passed without the leading 'v'. 
This was a mistake introduced in Azure provider manifest-gen tooling. All other platforms use the version directly with the leading 'v'.
This change is safe as there is nothing using the version tag, and we are on tech preview.
=> NO-JIRA: Update version variable in generate-ocp-manifests hook script

pkg/controllers/machinesetsync/machineset_sync_controller.go, pkg/controllers/machinesetsync/machineset_sync_controller_test.go, pkg/controllers/machinesync/machine_sync_controller.go, pkg/controllers/machinesync/machine_sync_controller_test.go, pkg/conversion/capi2mapi/machine.go, pkg/conversion/capi2mapi/machineset.go, pkg/conversion/capi2mapi/machineset_test.go, pkg/conversion/mapi2capi/machine_test.go, pkg/conversion/mapi2capi/machineset.go, pkg/conversion/mapi2capi/machineset_test.go, pkg/conversion/mapi2capi/util.go, pkg/conversion/test/fuzz/fuzz.go
This PR adds support to MachineSync and MachineSetSync controller for converting OwnerReferences in mirrored MachineSets, Machines and InfraMachines have correct ownerReferences.
=> OCPCLOUD-2716: Handle Machine owner references translation between MAPI and CAPI

pkg/conversion/capi2mapi/aws.go, pkg/conversion/capi2mapi/aws_fuzz_test.go
Hello! This is a PR to update some of the comments left behind during the conversion work.
The investigation discovered that the current behaviour is what we want, so I just updated some comments to leave information for future reference.
Thanks!
=> OCPCLOUD-2712: Update comments based on Security Group Investigation

pkg/controllers/machinesetsync/machineset_sync_controller.go, pkg/controllers/machinesync/machine_sync_controller.go, pkg/controllers/machinesync/machine_sync_controller_test.go, pkg/conversion/capi2mapi/aws.go, pkg/conversion/capi2mapi/aws_fuzz_test.go, pkg/conversion/capi2mapi/common.go, pkg/conversion/capi2mapi/machine.go, pkg/conversion/capi2mapi/machineset.go, pkg/conversion/capi2mapi/powervs.go, pkg/conversion/capi2mapi/powervs_fuzz_test.go, pkg/conversion/mapi2capi/aws.go, pkg/conversion/mapi2capi/aws_fuzz_test.go, pkg/conversion/mapi2capi/aws_test.go, pkg/conversion/mapi2capi/machine.go, pkg/conversion/mapi2capi/machine_test.go, pkg/conversion/mapi2capi/machineset.go, pkg/conversion/mapi2capi/machineset_test.go, pkg/conversion/mapi2capi/powervs.go, pkg/conversion/mapi2capi/util.go, pkg/conversion/test/fuzz/fuzz.go, pkg/util/maps.go, pkg/util/object.go, pkg/util/sync.go
This PR contains:
- assorted fixes to the sync controllers and the conversion libraries that I picked up while running the migration controllers doing full, real, back and forth MAPI->CAPI->MAPI migrations of machines and machine sets.
- full labels and annotations syncing between MAPI and CAPI, while also adding node labels and annotations propagation from CAPI machines down to their nodes
- machine sets selector bidirectional conversion
- improved diffing and diffs readability for machines and machine sets
- temporary hardcoded credentials secret conversion support for the default case to allow for migrations to momentarily work
- adds several `TODO(docs)` for lossy conversions that we might need to document (cc. @jeana-redhat)
=> OCPCLOUD-2880: label selector and labels conversion, fixes to sync controllers and conversions

cmd/machine-api-migration/main.go, pkg/controllers/machinemigration/machine_migration_controller.go, pkg/controllers/machinemigration/machine_migration_controller_test.go, pkg/controllers/machinemigration/suite_test.go, pkg/controllers/machinesetmigration/machineset_migration_controller.go, pkg/controllers/machinesetmigration/machineset_migration_controller_test.go, pkg/controllers/machinesetmigration/suite_test.go, pkg/controllers/machinesync/machine_sync_controller.go, pkg/conversion/capi2mapi/machine.go, pkg/conversion/capi2mapi/machineset.go, pkg/conversion/mapi2capi/machine.go, pkg/conversion/mapi2capi/machineset.go, pkg/conversion/test/fuzz/fuzz.go, pkg/util/annotations.go, pkg/util/conditions.go, pkg/util/finalizer.go, pkg/util/object.go, vendor/modules.txt, vendor/sigs.k8s.io/cluster-api/util/conditions/v1beta2/aggregate.go, vendor/sigs.k8s.io/cluster-api/util/conditions/v1beta2/doc.go, vendor/sigs.k8s.io/cluster-api/util/conditions/v1beta2/getter.go, vendor/sigs.k8s.io/cluster-api/util/conditions/v1beta2/matcher.go, vendor/sigs.k8s.io/cluster-api/util/conditions/v1beta2/merge_strategies.go, vendor/sigs.k8s.io/cluster-api/util/conditions/v1beta2/mirror.go, vendor/sigs.k8s.io/cluster-api/util/conditions/v1beta2/options.go, vendor/sigs.k8s.io/cluster-api/util/conditions/v1beta2/patch.go, vendor/sigs.k8s.io/cluster-api/util/conditions/v1beta2/setter.go, vendor/sigs.k8s.io/cluster-api/util/conditions/v1beta2/sort.go, vendor/sigs.k8s.io/cluster-api/util/conditions/v1beta2/summary.go
This PR adds the MAPI-CAPI migration controllers, resposible for handling the authoritativeness switching between MAPI and CAPI.
=> OCPCLOUD-2564: add migration controllers

hack/test.sh, pkg/controllers/infracluster/aws.go, pkg/conversion/capi2mapi/aws.go, pkg/conversion/capi2mapi/aws_test.go, pkg/conversion/mapi2capi/aws.go, pkg/conversion/mapi2capi/aws_fuzz_test.go, pkg/conversion/mapi2capi/aws_test.go
See individual commits for each piece of work.
Also modified the test.sh script so that I didn't have to run all test suites every time.
=> OCPCLOUD-2713: Handle credential fields in both mapi2capi and capi2mapi

pkg/controllers/machinemigration/machine_migration_controller.go, pkg/controllers/machinesetmigration/machineset_migration_controller.go, pkg/controllers/machinesync/machine_sync_controller.go, pkg/controllers/machinesync/machine_sync_controller_test.go, pkg/util/finalizer.go
This change adds deletion logic for Machines. 
It introduces a sync finalizer to coordinate synchronization of mirrored resources.
If we are reconciling deletions MAPI -> CAPI, we ensure the MAPI specific finalizers are removed before removing our sync finalizer.
If we are reconciling deletions CAPI -> MAPI, we ensure that the CAPI InfraMachine has it's specific (per provider) finalizer removed by the CAPI controllers, before removing our sync finalizer. This must happen *before* the CAPI Machine controller will remove the CAPI machine deletion finalizer. Once we observe this, we remove our sync finalizer allowing deletion of mirrored objects. 
This has been tested in both directions on a live cluster.
=> OCPCLOUD-2648: Machine sync controller deletion logic

cmd/cluster-capi-operator/main.go, cmd/machine-api-migration/main.go
We have seen lots of caching (Watches) being established on namespaces we don't actually care about. By default, controller runtime will cache all objects we fetch for all of the default namespaces.
For our controllers, we typically care about the managed namespace, and only want to fetch certain objects from other namespaces.
This PR splits out the specific objects that we watch from other namespaces so that we only cache those objects in the other namespaces and not every object we care about
=> NO-JIRA: Prevent caching CAPI objects across namespaces

manifests-gen/customizations.go, pkg/controllers/capiinstaller/capi_installer_controller.go
The API group was never meant to ship in openshift, we should be using v1 which has identical APIs
=> OCPBUGS-55947: Should not use v1beta1 of the AdmissionRegistration API group

pkg/controllers/machinesetsync/machineset_sync_controller.go, pkg/controllers/machinesetsync/machineset_sync_controller_test.go, pkg/controllers/machinesync/machine_sync_controller.go
This PR adds deletion logic to the MachineSetSync controller. 
59bde20875989f6aecd8f610324f02652dd92823 This change sets the deletion finalizer on both MAPI and CAPI machinesets when reconciling both directions.
236c7ee8fc8d447d3b3056bcbaa9fd0e3e874d7f handles deletion when the MAPI MS is authoritative 
b4ffb7a73bbc0f6d83575a7bf067614c7787010f handles deletion when a CAPI MS is authoritative
b1d1a1407c9d6e723c35c7d1756a856a939a34dc  Allows removal of non-authoritative MAPI machinesets
=>  OCPCLOUD-2943: MachineSet deletion logic 

e2e/aws_test.go, e2e/framework/machineset.go, pkg/controllers/common_consts.go, pkg/controllers/machinesetsync/machineset_sync_controller.go, pkg/controllers/machinesetsync/machineset_sync_controller_test.go, pkg/controllers/machinesync/machine_sync_controller_test.go, pkg/conversion/mapi2capi/aws.go, pkg/conversion/mapi2capi/powervs.go, pkg/conversion/test/fuzz/fuzz.go, pkg/util/hash.go, pkg/util/watch_filters.go
This PR adds missing logic when updating MAPI MachineSet that is AuthorativeAPI=MachineAPI.
Because CAPI Infrastructure machine templates are immutable, we need to recreate it.
The logic is as follows:
1. Create a new infrastructure machine template with hash of spec in its name to avoid name conflict.
2. Modify the CAPI machineSet to use the new machine template.
3. Delete old infrastructure machine template.
This PR also adds the `machine.openshift.io/cluster-api-machineset` label to infrastructure machine templates converted from MAPI. This label serves 2 purposes.
- It allows listing old infrastructure machine templates that were created from conversion and should be deleted. When the reconcile fails at step 3. Without the label, the CAPI machineSet after step 2 no longer points to …
=> OCPBUGS-54705: mapi2capi: Create new machine template when changing MAPI providerSpec

manifests/0000_30_cluster-api_10_webhooks.yaml
kind of post-cleanup of https://github.com/openshift/cluster-capi-operator/pull/145
reduce the unused number of yamls, cvo will not reconcile this yaml
it only works when upgrade from 4.15, can be removed in the newest version(4.20)
=> NO-JIRA: Remove manifest for validating-webhook-configuration

go.mod, pkg/test/envtest.go
This causes the envtests to automatically use a locally overridden openshift/api package. It continues to use the vendor directory by default while we use vendoring, but will also continue working seamlessly if we ever stop using vendoring.
=> NO-JIRA: Get openshift/api directory from packages

e2e/framework/machine.go, e2e/machine_migration_test.go
This is ready for review @sunzhaohua2 @miyadav @shellyyang1989 @JoelSpeed PTAL, thanks!
=> OCPCLOUD-2992: migration e2e for creating machine with authoritativeAPI ClusterAPI

e2e/e2e_test.go, e2e/mapimachines_test.go
e2e test for mapimachine creation when authoritativeAPI is machineapi
statusAPI should be updated to reflect correct authority
Synchronized condition is set
Synchronized generation is set correctly
Expect a paused CAPI Machine to be created to reflect the MAPI Machines
=> OCPCLOUD-2992: e2e test for mapimachine creation

pkg/conversion/capi2mapi/common.go, pkg/conversion/capi2mapi/machine_test.go, pkg/conversion/mapi2capi/machine_test.go, pkg/conversion/mapi2capi/util.go, pkg/util/annotations.go
Implements bi-directional conversion for mapi`s <-> capi's delete-machine annotations:
* mapi:  `machine.openshift.io/delete-machine`
* capi: `cluster.x-k8s.io/delete-machine`
=> OCPCLOUD-2871: Machine conversion for the delete-machine annotation and unit tests

manifests/0000_30_cluster-api_09_admission-policies.yaml, pkg/controllers/machinesync/machine_sync_controller_test.go
Hello. This is a draft PR for [OCPCLOUD-2714](https://issues.redhat.com/browse/OCPCLOUD-2714). It's in a drafted state until [Theo's PR here ](https://github.com/openshift/cluster-capi-operator/pull/321/files#) merges, as he's working on some VAP specific test suites, and it would make sense to wait until that's merged and updating this PR, instead of merging these messy tests :)
Thanks!
=> OCPCLOUD-2714: Add VAPs to prevent setting of CAPI fields that are not supported by MAPI
