openshift/cluster-capi-operator

Dockerfile
Dockerfile.rhel
Makefile
hack/go-get-tool.sh
hack/unit-tests.sh
hack/verify-diff.sh

Add `make unit|images|push` tasks, dockerfiles and a task for verifying vendor content

Additional repository setup

---

assets/core-capi/core-cluster-api-provider.yaml
assets/core-capi/core-cluster-api.yaml
assets/embed.go
assets/infrastructure-providers/infrastructure-aws-provider.yaml
assets/infrastructure-providers/infrastructure-aws.yaml
hack/import-assets.sh
hack/import-assets/main.go
hack/import-assets/providers.go
manifests/0000_30_cluster-api_00_credentials-request.yaml
manifests/0000_30_cluster-api_capi-operator_02_providers.configmap.yaml
manifests/0000_30_cluster-api_core-cluster-api_02_crd.yaml
manifests/0000_30_cluster-api_core-cluster-api_03_rbac.yaml
manifests/0000_30_cluster-api_infrastructure-aws_02_crd.yaml
manifests/0000_30_cluster-api_infrastructure-aws_03_rbac.yaml
providers-list.yaml

- Add CAPA to provider-list.yaml
- Update CAPI version in provider-list.yaml
- Filter out credentials secret that comes with provider manifests because our credentials are managed by CCO

Add CAPA to supported providers

---

pkg/controllers/secretsync/secret_sync_controller.go
pkg/controllers/secretsync/secret_sync_controller_test.go

Change user data secret from `userData` to `value` because all CAPI providers are using `value`.

Change user data secret

---

hack/import-assets/customizations.go
hack/import-assets/operator.go
hack/import-assets/providers.go

Instead of iterating through objects multiple times, we can do it in one go.

Refactor import-assets

---

pkg/controllers/cluster/cluster.go
pkg/controllers/cluster/cluster_test.go
vendor/modules.txt
vendor/sigs.k8s.io/cluster-api/util/conditions/doc.go
vendor/sigs.k8s.io/cluster-api/util/conditions/getter.go
vendor/sigs.k8s.io/cluster-api/util/conditions/matcher.go
vendor/sigs.k8s.io/cluster-api/util/conditions/matchers.go
vendor/sigs.k8s.io/cluster-api/util/conditions/merge.go
vendor/sigs.k8s.io/cluster-api/util/conditions/merge_strategies.go
vendor/sigs.k8s.io/cluster-api/util/conditions/patch.go
vendor/sigs.k8s.io/cluster-api/util/conditions/setter.go
vendor/sigs.k8s.io/cluster-api/util/conditions/unstructured.go
vendor/sigs.k8s.io/cluster-api/util/retry.go
vendor/sigs.k8s.io/cluster-api/util/util.go

Set control plane initialized condition to true, we should hardcode it before we get proper control plane management using CAPI.

Set control plane initialized condition

---

cmd/cluster-capi-operator/main.go
pkg/operatorstatus/operator_status.go

Fixes 2 bugs causing CI failures. As both fixes are required to pass CI this PR also includes https://github.com/openshift/cluster-capi-operator/pull/48

Fix outstanding CI failures

---

hack/assets/customizations.go
manifests/0000_30_cluster-api_capi-operator_11_deployment.upstream.yaml

Add openshift annotations to operator deployment

Add openshift annotations to operator deployment

---

pkg/controllers/kubeconfig/kubeconfig.go
pkg/controllers/kubeconfig/kubeconfig_test.go
pkg/controllers/kubeconfig/suite_test.go
pkg/test/cleanup.go
vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
vendor/k8s.io/client-go/testing/actions.go
vendor/k8s.io/client-go/testing/fake.go
vendor/k8s.io/client-go/testing/fixture.go
vendor/k8s.io/client-go/testing/interface.go
vendor/modules.txt
vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go

The token secret might expire, this PR makes sure that the secret is rotated every 30 minutes.

Bug 2089254: Rotate token secret if its older than 30 minutes

---

assets/infrastructure-providers/infrastructure-gcp.yaml
manifests/0000_30_cluster-api_infrastructure-gcp_02_crd.yaml
manifests/0000_30_cluster-api_infrastructure-gcp_03_rbac.yaml

Update CAPG after the latest rebase, all manifests are generated automatically using `make assets` command.

Bug 2099695: Update CAPG after rebase

---

pkg/webhook/cluster.go
pkg/webhook/infraprovider.go

This PR contains changes to add PowerVS as valid platform for webhooks

Add PowerVS platform to webhooks

---

assets/core-capi/core-cluster-api.yaml
assets/infrastructure-providers/infrastructure-aws.yaml
assets/infrastructure-providers/infrastructure-azure.yaml
assets/infrastructure-providers/infrastructure-gcp.yaml
cluster-api-operator.yaml
manifests/0000_30_cluster-api_02_crd.core-cluster-api.yaml
manifests/0000_30_cluster-api_02_crd.infrastructure-aws.yaml
manifests/0000_30_cluster-api_02_crd.infrastructure-azure.yaml
manifests/0000_30_cluster-api_02_crd.infrastructure-gcp.yaml
manifests/0000_30_cluster-api_02_crd.upstream.yaml
manifests/0000_30_cluster-api_02_providers.configmap.yaml
manifests/0000_30_cluster-api_02_service.upstream.yaml
manifests/0000_30_cluster-api_03_rbac-roles.core-cluster-api.yaml
manifests/0000_30_cluster-api_03_rbac-roles.infrastructure-azure.yaml
manifests/0000_30_cluster-api_11_deployment.upstream.yaml
providers-list.yaml

Bump manifests for CAPI components.
Generated by:
make assets

Bug 2087043: Update manifests to release-4.13

---

assets/infrastructure-providers/infrastructure-azure.yaml
manifests/0000_30_cluster-api_02_crd.infrastructure-azure.yaml

After updating CAPZ code, manifests have to be updated as well.
Generated by:
`make assets`

Fix assets

---

assets/core-capi/core-cluster-api.yaml
assets/infrastructure-providers/infrastructure-aws.yaml
assets/infrastructure-providers/infrastructure-azure.yaml
assets/infrastructure-providers/infrastructure-gcp.yaml
assets/infrastructure-providers/infrastructure-ibmcloud.yaml
hack/assets/customizations.go
manifests/0000_30_cluster-api_11_deployment.upstream.yaml

added logic to merge in workload annotations to deployments

OCPBUGS-10809: feat: add workload annotations

---

hack/e2e-openstack.sh

add openstack e2e testing script

NO-JIRA: e2e: add openstack testing script

---

.snyk

Hello! This is a PR to add a snyk file to exclude the vendors folder while scanning the repo. Thanks!

OCPBUGS-26121: Add Snyk file to exclude vendor directory on scan

---

manifests-gen/customizations.go

Update the manifest generator to not apply the:
`release.openshift.io/feature-set: CustomNoUpgrade,TechPreviewNoUpgrade` annotation to 
Core CAPI IPAM CRDs as we want to promote it to GA.

OCPCLOUD-2517: manifests-gen: promote Core CAPI IPAM CRDs to GA

---

cmd/cluster-capi-operator/main.go
e2e/vsphere_test.go
pkg/controllers/infracluster/aws.go
pkg/controllers/infracluster/infracluster_controller.go
pkg/controllers/infracluster/vsphere.go

OCPCLOUD-2207: Generate VSphereCluster

---

e2e/azure_test.go
pkg/controllers/infracluster/azure.go
pkg/controllers/infracluster/infracluster_controller.go

Hello! 
This is a PR for [OCPCLOUD-2205](https://issues.redhat.com/browse/OCPCLOUD-2206) to generate a GCPCluster resource for CAPI clusters. Thanks!

OCPCLOUD-2206: Generate AzureCluster resource for CAPI cluster

---

go.mod
go.sum
pkg/conversion/mapi2capi/machine.go
pkg/conversion/mapi2capi/machine_test.go
pkg/conversion/mapi2capi/machineset_test.go
vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1beta1/machine.go
vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1beta1/machineset.go
vendor/modules.txt

Add missing machine/machineset tests to the mapi2capi conversion pkg negative testing.

OCPCLOUD-2749: mapi2capi conversion pkg negative testing: add missing machine/machineset tests

---

pkg/conversion/mapi2capi/aws.go

@JoelSpeed @damdo , PTAL if its ok to get it merged ( very small , harmless ).

NO-JIRA: updated spell and comment

---

cmd/machine-api-migration/main.go

Updates the machine-api-migration cmd to:
- No longer crash, due to using a client from an uninitialised manager
- Have the appropriate schemes registered (so far)
- Stop using MetricsBindAddr, which is removed in 1.9 and use
DiagnosticsAddress instead. This avoids a port clash when starting the
manager.
Now the command runs without crashing, we won't cause the `cluster-capi-operator` deployment to crashloop.
```bash
I1127 13:42:59.722330   35247 main.go:201] MachineAPIMigration: starting AWS controllers
I1127 13:42:59.722605   35247 main.go:245] Starting manager
I1127 13:42:59.722849   35247 server.go:208] "Starting metrics server" logger="controller-runtime.metrics"
I1127 13:42:59.722874   35247 server.go:83] "starting server" name="health probe" addr="[::]:9441"
I1127 13:42:59.723277 …
```

OCPCLOUD-2647: Updates machine-api-migration cmd

---

manifests/0000_30_cluster-api_01_credentials-request.yaml
manifests/0000_30_cluster-api_02_service_account.yaml
manifests/0000_30_cluster-api_03_rbac_roles.yaml
manifests/0000_30_cluster-api_04_rbac_bindings.yaml
manifests/0000_30_cluster-api_10_webhooks.yaml

OCPCLOUD-2787: Add missing CustomNoUpgrade to manifests

---

pkg/conversion/capi2mapi/machine.go
pkg/conversion/mapi2capi/machine.go
pkg/conversion/test/fuzz/fuzz.go

Metadata propagation was split into multiple issues.

NO-JIRA: Update TODOs with new Jira issues

---

e2e/azure_test.go

https://github.com/openshift/installer/pull/9538 introduced some changes in how MAPZ machines get generated.
So we need to account for it when we generate the CAPZ machine from those.
Discussion context here: https://redhat-internal.slack.com/archives/C05KZA3NVU6/p1742824263449689

NO-JIRA: fix: e2e: azure conditionally set identity

---

e2e/go.mod
e2e/go.sum
e2e/vendor/modules.txt
go.mod
go.sum
vendor/modules.txt

Bump github.com/golang-jwt/jwt to v5.2.2

NO-JIRA: Bump github.com/golang-jwt/jwt to v5.2.2

---

pkg/controllers/machinesync/machine_sync_controller.go
pkg/controllers/machinesync/machine_sync_controller_test.go

When we have a machine with authoritativeAPI of CAPI, but no CAPI machine exists we want to run an initial MAPI -> CAPI sync.
This updates the logic in the machinesync controller to do this, starting the newly created CAPI machine unpaused.

OCPBUGS-55349,OCPBUGS-54970: Ensure CAPI machine when machine authority is CAPI

---

pkg/controllers/machinesync/machine_sync_controller.go

When a non-authoritative machine is issued a deletion, the deletion should be propagated to the authoritative machine as well.
Context: https://redhat-internal.slack.com/archives/GE2HQ9QP4/p1746777766970039

OCPBUGS-55985: fix: machine: propagate non-authoritative deletion

---

pkg/controllers/machinesync/machine_sync_controller.go
pkg/controllers/machinesync/machine_sync_controller_test.go

This PR fixes conversion of Machines that don't have an MachineSet owner.
With this change, the MAPI2CAPI conversion adds cluster ownerReference to the mirrored CAPI machine and fixes conversion of CAPI machines with Cluster ownerReference.

OCPBUGS-54703: Fix conversion of Machines without MachineSet
